name: Sync gh-pages
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: replace gh-pages with master
        run: git push origin --force master:gh-pages
